// demos/complete/angular-cli/src/app/components/album-box/album-box.component.ts
import { Component, Input } from '@angular/core';
import Album from '../../models/album';

@Component({
  selector: 'app-album-box',
  templateUrl: './album-box.component.html',
  styleUrls: ['./album-box.component.css']
})
export class AlbumBoxComponent {
  @Input() album: Album;

  constructor() { }

  get imageUrl() {
    return `assets/${this.album.id}.png`;
  }
}


<div class="box">
  <div class="columns">
    <div class="column">
      <figure class="image is-square">
        <img [src]="imageUrl" [alt]="album.title" />
      </figure>
    </div>
    <div class="column">
      <h2 class="title">{{ album.title }}</h2>
      <h3 class="subtitle">{{ album.artist }}</h3>
      <div>
        Category: {{ album.category }}
      </div>
    </div>
  </div>
</div>

// demos/complete/vue-cli/src/components/AlbumBox.vue
<template>
  <div class="column is-half">
    <div class="box">
      <div class="columns">
        <div class="column">
          <figure class="image is-square">
            <img v-bind:src="imageUrl" v-bind:alt="album.title" />
          </figure>
        </div>
        <div class="column">
          <h2 class="title">{{ album.title }}</h2>
          <h3 class="subtitle">{{ album.artist }}</h3>
          <div>
            Category: {{ album.category }}
          </div>
        </div>      
      </div>      
    </div>
  </div>
</template>

<script>
export default {
  name: 'AlbumBox',
  props: {
    album: {
      type: Object,
      required: true
    },
  },
  computed: {
    imageUrl() {
      return require(`../assets/${this.album.id}.png`);
    }
  },
}
</script>

<style scoped>
</style>
