// demos/basic/angular-cli/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import Album from './models/album';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  albums: Album[] = [];

  constructor(private http: HttpClient) { }

  handleViewDetails() {
    alert('View details!');
  }

  ngOnInit(): void {
    this.http.get<Album[]>('http://localhost:3000/albums')
      .subscribe(data => this.albums = data);
  }
}

<div>
  <div *ngFor="let album of albums">
    <app-album [album]="album" (onViewDetails)="handleViewDetails()"></app-album>
  </div>
</div>

// demos/basic/react-cli/src/App.js
import React, { Component } from 'react';
import './App.css';

function Album(props) {
  return (
    <div>
      <h2>{props.album.title}</h2>
      <button onClick={props.viewDetails}>View Details</button>
    </div>
  );
}

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      albums: []
    };
  }

  handleViewDetails = () => {
    alert('View details!');
  }

  componentDidMount() {
    fetch('http://localhost:3000/albums')
      .then(response => response.json())
      .then(data => {
        this.setState({
          albums: data
        });
      });
  }

  render() {
    return (
      <div>
        {this.state.albums.map(album => (
          <Album 
            album={album} 
            viewDetails={this.handleViewDetails} 
            key={album.id} />
        ))}
      </div>
    );
  }
}

export default App;
