// demos/complete/vue-cli/src/components/SearchBar.vue
<template>
  <div>
    <div class="columns">
      <div class="column">
        <input type="text" v-model.trim="searchQuery" 
          v-on:keyup.enter="search" class="input is-medium" placeholder="Enter search query..." />
      </div>
      <div class="column is-narrow">
        <div class="select is-medium">
          <select v-model="searchCategory">
            <option value="">Select a category...</option>
            <option v-for="category in categories" 
              v-bind:value="category" v-bind:key="category">{{ category }}</option>
          </select>
        </div>
      </div>
      <div class="column is-narrow">
        <button v-on:click="search" class="button is-primary is-medium">Search</button>&nbsp;
        <button v-on:click="clearSearch" class="button is-warning is-medium">Clear</button>    
      </div>
    </div>

    <div v-show="showSearchCriteria && (searchQuery || searchCategory)" class="notification is-info">
      <span v-show="searchQuery">Search Query: {{ searchQuery }}</span><span v-show="searchQuery && searchCategory">, </span><span v-show="searchCategory">Search Category: {{ searchCategory }}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'SearchBar',
  props: {
    categories: {
      type: Array,
      required: true
    },
    showSearchCriteria: {
      type: Boolean,
      default: false
    }
  },  
  data: function() {
    return {
      searchQuery: '',
      searchCategory: ''
    };
  },
  methods: {
    search() {
      this.$emit('search', this.searchQuery, this.searchCategory);
    },
    clearSearch() {
      this.searchQuery = '';
      this.searchCategory = '';      
      this.$emit('clear-search');
    }
  }
}
</script>

<style scoped>
</style>

// demos/complete/react-cli/src/components/SearchBar.js
import React, { Component } from 'react';

function SearchCriteria(props) {
  const {showSearchCriteria, searchQuery, searchCategory} = props;

  console.log(`showSearchCriteria: ${showSearchCriteria}, searchQuery: ${searchQuery}, searchCategory: ${searchCategory}`);

  if (showSearchCriteria && (searchQuery || searchCategory)) {
    const content = [];

    if (searchQuery) {
      content.push(
        <span>Search Query: {searchQuery}</span>
      );
    }

    if (searchQuery && searchCategory) {
      content.push(<span>, </span>);
    }

    if (searchCategory) {
      content.push(
        <span>Search Category: {searchCategory}</span>
      );        
    }

    return (
      <div className="notification is-info">
        {content}
      </div>    
    );
  } else {
    return null;
  }
}

export default class SearchBar extends Component {
  constructor(props) {
    super(props);

    this.state = {
      searchQuery: '',
      searchCategory: ''
    };
  }

  handleSearchQueryChange = (event) => {
    this.setState({searchQuery: event.target.value});
  }

  handleSearchQueryKeyPress = (event) => {
    if (event.charCode === 13) {
      this.search();      
    }
  }

  handleSearchCategoryChange = (event) => {
    this.setState({searchCategory: event.target.value});
  }
  
  search = () => {
    this.props.search(
      this.state.searchQuery,
      this.state.searchCategory
    );
  }

  clearSearch = () => {
    this.setState({
      searchQuery: '',
      searchCategory: ''
    });
    this.props.clearSearch();
  }

  render() {
    const searchCategoryOptions = [
      <option value="" key="">Select a category...</option>
    ];

    this.props.categories.forEach(category => {
      searchCategoryOptions.push(
        <option value={category} key={category}>{category}</option>
      );
    });
    
    return (
      <div>
        <div className="columns">
          <div className="column">
            <input type="text" value={this.state.searchQuery} onChange={this.handleSearchQueryChange} onKeyPress={this.handleSearchQueryKeyPress} className="input is-medium" placeholder="Enter search query..." />
          </div>
          <div className="column is-narrow">
            <div className="select is-medium">
              <select value={this.state.searchCategory} onChange={this.handleSearchCategoryChange}>
                {searchCategoryOptions}
              </select>
            </div>
          </div>
          <div className="column is-narrow">
            <button onClick={this.search} className="button is-primary is-medium">Search</button>&nbsp;
            <button onClick={this.clearSearch} className="button is-warning is-medium">Clear</button>    
          </div>
        </div>

        <SearchCriteria 
          showSearchCriteria={false} 
          searchQuery={this.state.searchQuery} 
          searchCategory={this.state.searchCategory} />  

      </div>
    );
  }
}
